// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoServidorInformantes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnToServidorFromInformanteClient is the client API for ConnToServidorFromInformante service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnToServidorFromInformanteClient interface {
	Comando(ctx context.Context, in *MensajeToServidor, opts ...grpc.CallOption) (*Respuesta, error)
}

type connToServidorFromInformanteClient struct {
	cc grpc.ClientConnInterface
}

func NewConnToServidorFromInformanteClient(cc grpc.ClientConnInterface) ConnToServidorFromInformanteClient {
	return &connToServidorFromInformanteClient{cc}
}

func (c *connToServidorFromInformanteClient) Comando(ctx context.Context, in *MensajeToServidor, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/grpc.ConnToServidorFromInformante/Comando", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnToServidorFromInformanteServer is the server API for ConnToServidorFromInformante service.
// All implementations must embed UnimplementedConnToServidorFromInformanteServer
// for forward compatibility
type ConnToServidorFromInformanteServer interface {
	Comando(context.Context, *MensajeToServidor) (*Respuesta, error)
	mustEmbedUnimplementedConnToServidorFromInformanteServer()
}

// UnimplementedConnToServidorFromInformanteServer must be embedded to have forward compatible implementations.
type UnimplementedConnToServidorFromInformanteServer struct {
}

func (UnimplementedConnToServidorFromInformanteServer) Comando(context.Context, *MensajeToServidor) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Comando not implemented")
}
func (UnimplementedConnToServidorFromInformanteServer) mustEmbedUnimplementedConnToServidorFromInformanteServer() {
}

// UnsafeConnToServidorFromInformanteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnToServidorFromInformanteServer will
// result in compilation errors.
type UnsafeConnToServidorFromInformanteServer interface {
	mustEmbedUnimplementedConnToServidorFromInformanteServer()
}

func RegisterConnToServidorFromInformanteServer(s grpc.ServiceRegistrar, srv ConnToServidorFromInformanteServer) {
	s.RegisterService(&ConnToServidorFromInformante_ServiceDesc, srv)
}

func _ConnToServidorFromInformante_Comando_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MensajeToServidor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnToServidorFromInformanteServer).Comando(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnToServidorFromInformante/Comando",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnToServidorFromInformanteServer).Comando(ctx, req.(*MensajeToServidor))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnToServidorFromInformante_ServiceDesc is the grpc.ServiceDesc for ConnToServidorFromInformante service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnToServidorFromInformante_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ConnToServidorFromInformante",
	HandlerType: (*ConnToServidorFromInformanteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Comando",
			Handler:    _ConnToServidorFromInformante_Comando_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servidorInformante.proto",
}
