// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: servidorBroker.proto

package protoServidorBroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MensajeLeia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comando       string `protobuf:"bytes,1,opt,name=comando,proto3" json:"comando,omitempty"`
	NombrePlaneta string `protobuf:"bytes,2,opt,name=nombre_planeta,json=nombrePlaneta,proto3" json:"nombre_planeta,omitempty"`
	NombreCiudad  string `protobuf:"bytes,3,opt,name=nombre_ciudad,json=nombreCiudad,proto3" json:"nombre_ciudad,omitempty"`
}

func (x *MensajeLeia) Reset() {
	*x = MensajeLeia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidorBroker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MensajeLeia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeLeia) ProtoMessage() {}

func (x *MensajeLeia) ProtoReflect() protoreflect.Message {
	mi := &file_servidorBroker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeLeia.ProtoReflect.Descriptor instead.
func (*MensajeLeia) Descriptor() ([]byte, []int) {
	return file_servidorBroker_proto_rawDescGZIP(), []int{0}
}

func (x *MensajeLeia) GetComando() string {
	if x != nil {
		return x.Comando
	}
	return ""
}

func (x *MensajeLeia) GetNombrePlaneta() string {
	if x != nil {
		return x.NombrePlaneta
	}
	return ""
}

func (x *MensajeLeia) GetNombreCiudad() string {
	if x != nil {
		return x.NombreCiudad
	}
	return ""
}

type ServidorRespuestaLeia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumeroRebeldes    string  `protobuf:"bytes,1,opt,name=numero_rebeldes,json=numeroRebeldes,proto3" json:"numero_rebeldes,omitempty"`
	Vector            []int32 `protobuf:"varint,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	IpServidorFulcrum string  `protobuf:"bytes,3,opt,name=ip_servidor_fulcrum,json=ipServidorFulcrum,proto3" json:"ip_servidor_fulcrum,omitempty"`
}

func (x *ServidorRespuestaLeia) Reset() {
	*x = ServidorRespuestaLeia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidorBroker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServidorRespuestaLeia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServidorRespuestaLeia) ProtoMessage() {}

func (x *ServidorRespuestaLeia) ProtoReflect() protoreflect.Message {
	mi := &file_servidorBroker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServidorRespuestaLeia.ProtoReflect.Descriptor instead.
func (*ServidorRespuestaLeia) Descriptor() ([]byte, []int) {
	return file_servidorBroker_proto_rawDescGZIP(), []int{1}
}

func (x *ServidorRespuestaLeia) GetNumeroRebeldes() string {
	if x != nil {
		return x.NumeroRebeldes
	}
	return ""
}

func (x *ServidorRespuestaLeia) GetVector() []int32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *ServidorRespuestaLeia) GetIpServidorFulcrum() string {
	if x != nil {
		return x.IpServidorFulcrum
	}
	return ""
}

var File_servidorBroker_proto protoreflect.FileDescriptor

var file_servidorBroker_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x73, 0x0a, 0x0b,
	0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x4c, 0x65, 0x69, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x63, 0x69, 0x75, 0x64, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x43, 0x69, 0x75, 0x64, 0x61,
	0x64, 0x22, 0x88, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x4c, 0x65, 0x69, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x6e,
	0x75, 0x6d, 0x65, 0x72, 0x6f, 0x5f, 0x72, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x62, 0x65,
	0x6c, 0x64, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x13,
	0x69, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x66, 0x75, 0x6c, 0x63,
	0x72, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x69, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x32, 0x62, 0x0a, 0x18,
	0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x46, 0x72,
	0x6f, 0x6d, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x14, 0x4c, 0x65, 0x69, 0x61,
	0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73,
	0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x4c,
	0x65, 0x69, 0x61, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x64, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x4c, 0x65, 0x69, 0x61,
	0x42, 0x3f, 0x5a, 0x3d, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6c, 0x6b, 0x69, 0x6d, 0x6f, 0x2f, 0x49,
	0x4e, 0x46, 0x33, 0x34, 0x33, 0x2d, 0x54, 0x61, 0x72, 0x65, 0x61, 0x2d, 0x33, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servidorBroker_proto_rawDescOnce sync.Once
	file_servidorBroker_proto_rawDescData = file_servidorBroker_proto_rawDesc
)

func file_servidorBroker_proto_rawDescGZIP() []byte {
	file_servidorBroker_proto_rawDescOnce.Do(func() {
		file_servidorBroker_proto_rawDescData = protoimpl.X.CompressGZIP(file_servidorBroker_proto_rawDescData)
	})
	return file_servidorBroker_proto_rawDescData
}

var file_servidorBroker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_servidorBroker_proto_goTypes = []interface{}{
	(*MensajeLeia)(nil),           // 0: grpc.MensajeLeia
	(*ServidorRespuestaLeia)(nil), // 1: grpc.ServidorRespuestaLeia
}
var file_servidorBroker_proto_depIdxs = []int32{
	0, // 0: grpc.ConnToServidorFromBroker.LeiaGetNumberRebelds:input_type -> grpc.MensajeLeia
	1, // 1: grpc.ConnToServidorFromBroker.LeiaGetNumberRebelds:output_type -> grpc.ServidorRespuestaLeia
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_servidorBroker_proto_init() }
func file_servidorBroker_proto_init() {
	if File_servidorBroker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servidorBroker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MensajeLeia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servidorBroker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServidorRespuestaLeia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servidorBroker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servidorBroker_proto_goTypes,
		DependencyIndexes: file_servidorBroker_proto_depIdxs,
		MessageInfos:      file_servidorBroker_proto_msgTypes,
	}.Build()
	File_servidorBroker_proto = out.File
	file_servidorBroker_proto_rawDesc = nil
	file_servidorBroker_proto_goTypes = nil
	file_servidorBroker_proto_depIdxs = nil
}
