// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoServidorBroker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnToServidorFromBrokerClient is the client API for ConnToServidorFromBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnToServidorFromBrokerClient interface {
	LeiaGetNumberRebelds(ctx context.Context, in *MensajeLeia, opts ...grpc.CallOption) (*RespuestaLeia, error)
}

type connToServidorFromBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewConnToServidorFromBrokerClient(cc grpc.ClientConnInterface) ConnToServidorFromBrokerClient {
	return &connToServidorFromBrokerClient{cc}
}

func (c *connToServidorFromBrokerClient) LeiaGetNumberRebelds(ctx context.Context, in *MensajeLeia, opts ...grpc.CallOption) (*RespuestaLeia, error) {
	out := new(RespuestaLeia)
	err := c.cc.Invoke(ctx, "/grpc.ConnToServidorFromBroker/LeiaGetNumberRebelds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnToServidorFromBrokerServer is the server API for ConnToServidorFromBroker service.
// All implementations must embed UnimplementedConnToServidorFromBrokerServer
// for forward compatibility
type ConnToServidorFromBrokerServer interface {
	LeiaGetNumberRebelds(context.Context, *MensajeLeia) (*RespuestaLeia, error)
	mustEmbedUnimplementedConnToServidorFromBrokerServer()
}

// UnimplementedConnToServidorFromBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedConnToServidorFromBrokerServer struct {
}

func (UnimplementedConnToServidorFromBrokerServer) LeiaGetNumberRebelds(context.Context, *MensajeLeia) (*RespuestaLeia, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeiaGetNumberRebelds not implemented")
}
func (UnimplementedConnToServidorFromBrokerServer) mustEmbedUnimplementedConnToServidorFromBrokerServer() {
}

// UnsafeConnToServidorFromBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnToServidorFromBrokerServer will
// result in compilation errors.
type UnsafeConnToServidorFromBrokerServer interface {
	mustEmbedUnimplementedConnToServidorFromBrokerServer()
}

func RegisterConnToServidorFromBrokerServer(s grpc.ServiceRegistrar, srv ConnToServidorFromBrokerServer) {
	s.RegisterService(&ConnToServidorFromBroker_ServiceDesc, srv)
}

func _ConnToServidorFromBroker_LeiaGetNumberRebelds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MensajeLeia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnToServidorFromBrokerServer).LeiaGetNumberRebelds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnToServidorFromBroker/LeiaGetNumberRebelds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnToServidorFromBrokerServer).LeiaGetNumberRebelds(ctx, req.(*MensajeLeia))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnToServidorFromBroker_ServiceDesc is the grpc.ServiceDesc for ConnToServidorFromBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnToServidorFromBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ConnToServidorFromBroker",
	HandlerType: (*ConnToServidorFromBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeiaGetNumberRebelds",
			Handler:    _ConnToServidorFromBroker_LeiaGetNumberRebelds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servidorBroker.proto",
}
