// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoServidorBroker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnToServidorClient is the client API for ConnToServidor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnToServidorClient interface {
	LeiaGetNumberRebelds(ctx context.Context, in *MensajeLeia, opts ...grpc.CallOption) (*RespuestaLeia, error)
}

type connToServidorClient struct {
	cc grpc.ClientConnInterface
}

func NewConnToServidorClient(cc grpc.ClientConnInterface) ConnToServidorClient {
	return &connToServidorClient{cc}
}

func (c *connToServidorClient) LeiaGetNumberRebelds(ctx context.Context, in *MensajeLeia, opts ...grpc.CallOption) (*RespuestaLeia, error) {
	out := new(RespuestaLeia)
	err := c.cc.Invoke(ctx, "/grpc.ConnToServidor/LeiaGetNumberRebelds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnToServidorServer is the server API for ConnToServidor service.
// All implementations must embed UnimplementedConnToServidorServer
// for forward compatibility
type ConnToServidorServer interface {
	LeiaGetNumberRebelds(context.Context, *MensajeLeia) (*RespuestaLeia, error)
	mustEmbedUnimplementedConnToServidorServer()
}

// UnimplementedConnToServidorServer must be embedded to have forward compatible implementations.
type UnimplementedConnToServidorServer struct {
}

func (UnimplementedConnToServidorServer) LeiaGetNumberRebelds(context.Context, *MensajeLeia) (*RespuestaLeia, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeiaGetNumberRebelds not implemented")
}
func (UnimplementedConnToServidorServer) mustEmbedUnimplementedConnToServidorServer() {}

// UnsafeConnToServidorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnToServidorServer will
// result in compilation errors.
type UnsafeConnToServidorServer interface {
	mustEmbedUnimplementedConnToServidorServer()
}

func RegisterConnToServidorServer(s grpc.ServiceRegistrar, srv ConnToServidorServer) {
	s.RegisterService(&ConnToServidor_ServiceDesc, srv)
}

func _ConnToServidor_LeiaGetNumberRebelds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MensajeLeia)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnToServidorServer).LeiaGetNumberRebelds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnToServidor/LeiaGetNumberRebelds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnToServidorServer).LeiaGetNumberRebelds(ctx, req.(*MensajeLeia))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnToServidor_ServiceDesc is the grpc.ServiceDesc for ConnToServidor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnToServidor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ConnToServidor",
	HandlerType: (*ConnToServidorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeiaGetNumberRebelds",
			Handler:    _ConnToServidor_LeiaGetNumberRebelds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servidorBroker.proto",
}
