// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoBrokerLeia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnToBrokerClient is the client API for ConnToBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnToBrokerClient interface {
	GetNumberRebelds(ctx context.Context, in *MensajeToBroker, opts ...grpc.CallOption) (*Respuesta, error)
}

type connToBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewConnToBrokerClient(cc grpc.ClientConnInterface) ConnToBrokerClient {
	return &connToBrokerClient{cc}
}

func (c *connToBrokerClient) GetNumberRebelds(ctx context.Context, in *MensajeToBroker, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/grpc.ConnToBroker/GetNumberRebelds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnToBrokerServer is the server API for ConnToBroker service.
// All implementations must embed UnimplementedConnToBrokerServer
// for forward compatibility
type ConnToBrokerServer interface {
	GetNumberRebelds(context.Context, *MensajeToBroker) (*Respuesta, error)
	mustEmbedUnimplementedConnToBrokerServer()
}

// UnimplementedConnToBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedConnToBrokerServer struct {
}

func (UnimplementedConnToBrokerServer) GetNumberRebelds(context.Context, *MensajeToBroker) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumberRebelds not implemented")
}
func (UnimplementedConnToBrokerServer) mustEmbedUnimplementedConnToBrokerServer() {}

// UnsafeConnToBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnToBrokerServer will
// result in compilation errors.
type UnsafeConnToBrokerServer interface {
	mustEmbedUnimplementedConnToBrokerServer()
}

func RegisterConnToBrokerServer(s grpc.ServiceRegistrar, srv ConnToBrokerServer) {
	s.RegisterService(&ConnToBroker_ServiceDesc, srv)
}

func _ConnToBroker_GetNumberRebelds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MensajeToBroker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnToBrokerServer).GetNumberRebelds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnToBroker/GetNumberRebelds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnToBrokerServer).GetNumberRebelds(ctx, req.(*MensajeToBroker))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnToBroker_ServiceDesc is the grpc.ServiceDesc for ConnToBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnToBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ConnToBroker",
	HandlerType: (*ConnToBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumberRebelds",
			Handler:    _ConnToBroker_GetNumberRebelds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brokerLeia.proto",
}
