// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoBrokerInformantes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnToBrokerFromInformanteClient is the client API for ConnToBrokerFromInformante service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnToBrokerFromInformanteClient interface {
	ObtenerDireccion(ctx context.Context, in *MensajeToBroker, opts ...grpc.CallOption) (*Respuesta, error)
}

type connToBrokerFromInformanteClient struct {
	cc grpc.ClientConnInterface
}

func NewConnToBrokerFromInformanteClient(cc grpc.ClientConnInterface) ConnToBrokerFromInformanteClient {
	return &connToBrokerFromInformanteClient{cc}
}

func (c *connToBrokerFromInformanteClient) ObtenerDireccion(ctx context.Context, in *MensajeToBroker, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/grpc.ConnToBrokerFromInformante/ObtenerDireccion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnToBrokerFromInformanteServer is the server API for ConnToBrokerFromInformante service.
// All implementations must embed UnimplementedConnToBrokerFromInformanteServer
// for forward compatibility
type ConnToBrokerFromInformanteServer interface {
	ObtenerDireccion(context.Context, *MensajeToBroker) (*Respuesta, error)
	mustEmbedUnimplementedConnToBrokerFromInformanteServer()
}

// UnimplementedConnToBrokerFromInformanteServer must be embedded to have forward compatible implementations.
type UnimplementedConnToBrokerFromInformanteServer struct {
}

func (UnimplementedConnToBrokerFromInformanteServer) ObtenerDireccion(context.Context, *MensajeToBroker) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerDireccion not implemented")
}
func (UnimplementedConnToBrokerFromInformanteServer) mustEmbedUnimplementedConnToBrokerFromInformanteServer() {
}

// UnsafeConnToBrokerFromInformanteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnToBrokerFromInformanteServer will
// result in compilation errors.
type UnsafeConnToBrokerFromInformanteServer interface {
	mustEmbedUnimplementedConnToBrokerFromInformanteServer()
}

func RegisterConnToBrokerFromInformanteServer(s grpc.ServiceRegistrar, srv ConnToBrokerFromInformanteServer) {
	s.RegisterService(&ConnToBrokerFromInformante_ServiceDesc, srv)
}

func _ConnToBrokerFromInformante_ObtenerDireccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MensajeToBroker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnToBrokerFromInformanteServer).ObtenerDireccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ConnToBrokerFromInformante/ObtenerDireccion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnToBrokerFromInformanteServer).ObtenerDireccion(ctx, req.(*MensajeToBroker))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnToBrokerFromInformante_ServiceDesc is the grpc.ServiceDesc for ConnToBrokerFromInformante service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnToBrokerFromInformante_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ConnToBrokerFromInformante",
	HandlerType: (*ConnToBrokerFromInformanteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerDireccion",
			Handler:    _ConnToBrokerFromInformante_ObtenerDireccion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brokerInformantes.proto",
}
